#include <stdexcept>

// void test1()
// {
//     try
//     {
//         /* code */
//     }
//     catch(const std::exception& e)
//     {
//         std::cerr << e.what() << '\n';
//     }
// }